/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "allocator.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_allocator_initialization_not_null(void);
extern void test_allocator_alloc_success(void);
extern void test_allocator_alloc_error_below_min_block_size(void);
extern void test_allocator_alloc_error_above_max_block_size(void);
extern void test_allocator_free_error_on_empty_buffer(void);
extern void test_allocator_many_allocs(void);
extern void test_allocator_many_allocs_and_frees(void);
extern void test_allocator_allocs_and_frees_different_sizes(void);
extern void test_allocator_peek_error_on_empty_buffer(void);
extern void test_allocator_peek_last_alloc(void);
extern void test_allocator_check_peeked_data(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("tests/test_allocator.c");
  run_test(test_allocator_initialization_not_null, "test_allocator_initialization_not_null", 13);
  run_test(test_allocator_alloc_success, "test_allocator_alloc_success", 20);
  run_test(test_allocator_alloc_error_below_min_block_size, "test_allocator_alloc_error_below_min_block_size", 29);
  run_test(test_allocator_alloc_error_above_max_block_size, "test_allocator_alloc_error_above_max_block_size", 38);
  run_test(test_allocator_free_error_on_empty_buffer, "test_allocator_free_error_on_empty_buffer", 47);
  run_test(test_allocator_many_allocs, "test_allocator_many_allocs", 53);
  run_test(test_allocator_many_allocs_and_frees, "test_allocator_many_allocs_and_frees", 72);
  run_test(test_allocator_allocs_and_frees_different_sizes, "test_allocator_allocs_and_frees_different_sizes", 107);
  run_test(test_allocator_peek_error_on_empty_buffer, "test_allocator_peek_error_on_empty_buffer", 130);
  run_test(test_allocator_peek_last_alloc, "test_allocator_peek_last_alloc", 142);
  run_test(test_allocator_check_peeked_data, "test_allocator_check_peeked_data", 159);

  return UnityEnd();
}
